# Generated by Django 5.0.2 on 2024-03-03 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('necessario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('ano_fundacao', models.PositiveIntegerField(help_text='Ano que o Clube foi criado', verbose_name='Ano Fundação')),
                ('divisao', models.CharField(choices=[('A', 'Série A'), ('B', 'Série B'), ('C', 'Série C'), ('D', 'Série D'), ('S', 'Sem Série')], default='S', max_length=64, null=True, verbose_name='Divisão')),
                ('modalidade', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='F', max_length=2)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='necessario.cidade')),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clubes',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('numero_camisa', models.PositiveIntegerField()),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futebol.clube')),
            ],
            options={
                'verbose_name_plural': 'Jogadores',
            },
        ),
    ]
